ploigos/ploigos-containers

.github/workflows/tssc-maven-pr.yaml, tssc-maven/Dockerfile.ubi8
Fix permissions of .m2 directory
=> Fix permissions of .m2

tssc-base/Dockerfile.ubi8
=> NAPSSPO-597 - add sops to tssc-base image

README.md, manual-publish.sh
add script and doc for manually publishing images
=> add script and doc for manually publishing images

.github/workflows/publish.yaml, README.md, tssc-tool-helm/Dockerfile, tssc-tool-helm/Dockerfile.ubi8, tssc-tool-helm/README.md
Adds a tssc-tool-helm image.
Testing has been baked into the github workflow.
=> add helm image

tssc-tool-helm/Dockerfile.ubi8
none root user can not use helm plugins installed by root user
set g+w on all recurisve files/dirs under the helm plugins dir
=> give gid=0 write permissions to all plugin files

README.md
fix badges to point at new repo
=> readme - fix badges

ploigos-base/Containerfile.ubi8
update to use 0.14.0 of tssc python package as the Ploigos step runner package
=> update to use tssc python lib 0.14.0

.github/workflows/publish.yaml
=> upgrade docker/build-push-action to v2.2.1

.github/workflows/publish.yaml, ploigos-base/Containerfile.ubi8
Install the [yq](https://github.com/mikefarah/yq) tool in the ploigos-base image for use for munging yaml.
Chosen over https://pypi.org/project/yq/ for https://github.com/mikefarah/yq better handling of comments and formating
=> ploigos-base - add yq

.github/workflows/publish.yaml
Adding rekor container to the github actions publish workflow
=> Adding rekor to the publish workflow

.github/workflows/publish.yaml, README.md, ploigos-tool-containers/ploigos-tool-containers-entrypoint.sh, ploigos-tool-jkube/Containerfile, ploigos-tool-jkube/Containerfile.ubi8, ploigos-tool-jkube/README.md, ploigos-tool-jkube/ploigos-tool-jkube-entrypoint.sh
add an image that can do [jkube](https://www.eclipse.org/jkube/) container builds.
=> add ploigos-tool-jkube

ploigos-tool-maven/Containerfile.ubi8
currently we install maven from package which installs ancient (3.5) maven. need newer maven.
Mostly we want access to the `--no-transfer-progress` option which doesnt exist in maven 3.5
=> install newer maven

ploigos-tool-helm/Containerfile.ubi8
zendesk/helm-secrets project deprecated and replaced by jkroepke/helm-secrets
=> zendesk/helm-secrets project deprecated and replaced by jkroepke/helm-secrets

ploigos-base/Containerfile.ubi8
This fixes issue of missing locale errors and warnings.
=> change locale to fix warnings

README.md, argocd-repo-server-sops/Containerfile.ubi8, argocd-repo-server-sops/README.md, argocd-repo-server-sops/helm-wrapper.sh
Describe the contents of the PR
=> argocd repo server sops

.github/workflows/publish.yaml, README.md, ploigos-tool-containers/Containerfile.ubi8, ploigos-tool-containers/README.md, ploigos-tool-jkube/Containerfile.ubi8
add s2i to ploigos-tool-containers
No
=> ploigos-tool-containers - add s2i

.github/workflows/publish.yaml
Adding JDK 17 images, as needed for an existing Ploigos pipeline.
No
TBD; this was a change in GitHub Actions, not any Containerfiles. Can this be tested locally?
=> Add tool and build containers for JDK 17

.github/scripts/determine-image-version.sh, .github/workflows/publish.yaml
fix old busted ci
* update github actions to latest versions
* fix various deprication errors
* use new-ish native concurency
* disable jkube builds - see https://github.com/ploigos/ploigos-containers/issues/112
No
=> ci - 2023 fixes

.github/workflows/publish.yaml, README.md, ploigos-base/Containerfile.ubi9, ploigos-ci-agent-jenkins/Containerfile.ubi9, ploigos-jenkins-init/Containerfile.ubi9, ploigos-tool-argocd/Containerfile.ubi9, ploigos-tool-autogov/Containerfile.ubi9, ploigos-tool-config-lint/Containerfile.ubi9, ploigos-tool-containers/Containerfile.ubi9, ploigos-tool-helm/Containerfile.ubi9, ploigos-tool-java/Containerfile.ubi9, ploigos-tool-javascript/Containerfile.ubi9, ploigos-tool-jkube/Containerfile.ubi9, ploigos-tool-maven/Containerfile.ubi9, ploigos-tool-openscap/Containerfile.ubi9, ploigos-tool-sonar/Containerfile.ubi9
switching to UBI base image with updates to other libraries as needed for cms support
No
Tested with Jenkins CICD Ploigos implementation and https://pypi.org/project/ploigos-step-runner/2.0.0rc4/
=> adding ubi9

ploigos-tool-autogov/Containerfile.ubi8, ploigos-tool-autogov/Containerfile.ubi9, ploigos-tool-autogov/contrib/centos.repo
merge autogov to gradle branch to fix CI build
=> merge autogov to gradle branch to fix CI build
